---
language: python
python: "3.8"

env:
  ansible:
    - ANSIBLE_VERSION=latest

dist: xenial

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

before_install:
  - sudo apt-get update -qq

install:
  # Install ansible
  - pip install ansible==$ANSIBLE_VERSION ansible_tower_cli

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Install AWX locally
  - ansible-playbook -i tests/inventory.yml installer/install.yml -e @vars.yml
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory.yml --syntax-check
  # Run playbook to populate awx
  - ansible-playbook tests/test.yml -i tests/inventory.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
