---
language: python
python: "3.8"

env:
  - ANSIBLE_VERSION=latest ANSIBLE_HOST_KEY_CHECKING=False

dist: xenial

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
      - python-pip

before_install:
  - sudo apt-get update -qq

install:
  # Install ansible
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible ansible_tower_cli docker-compose; else pip install ansible==$ANSIBLE_VERSION ansible_tower_cli docker-compose; fi

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Install AWX locally
  - git clone --depth 1 https://github.com/ansible/awx.git awx-tmp
  - cd awx-tmp
  # https://github.com/ansible/awx/blob/devel/INSTALL.md
  - ansible-playbook -i installer/inventory installer/install.yml
  # Basic role syntax check
  - cd ../
  - ansible-playbook -i tests/inventory.yml tests/test.yml --syntax-check
  # TODO: This will fail because we need to set a tower user name ans password variable
  # Run playbook to populate awx
  - ansible-playbook -i tests/inventory.yml tests/test.yml

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
