---

- name: Create Credentials
  # As you see here, defaults are omit to help with the _kind_ of credential
  tower_credential:
    name: "{{ item.name }}"
    organization: "{{ item.organization }}"
    state: "{{ item.state | default('present') }}"
    kind: "{{ item.kind }}"
    ssh_key_data: "{{ item.ssh_key | default(omit)}}"
    ssh_key_unlock: "{{ item.ssh_passphrase | default(omit)}}"
    username: "{{ item.user | default(omit)}}"
    password: "{{ item.password | default(omit)}}"
    vault_password: "{{ item.vault_password | default(omit)}}"
    validate_certs: False
  with_items: "{{ awx_creds }}"
  register: credential_creation
  no_log: True # Verbose will expose the auth detail (we don't want that)
